### ISSUE TITLE
Passing Parameters

### ISSUE THREAD

**Issue by captDaylight** [bebraw/pingdom-api#14]
In the docs it says:

> If the endpoint calls for a parameter, pass this in using the "target" field in options.

But I feel I'm missing something, isn't the checkId passed as the target? For example in this example the target is the checkId:
```javascript
pingdomApi.getChecks({
  target: 'someCheckId',
  qs: {
    limit: 10
  }
}, function (err, checks, response){
  console.log(err, checks);
});
```

So for the sake of an example, say I'm trying to get [Summary.outage](https://www.pingdom.com/resources/api/2.1#ResourceSummary.outage):
```javascript
pingdomApi.getSummaryOutage({
  target: someCheckId,
  // from: now - month
  // to: now
})
```

**Comment by bebraw** [comment]
Hi,

It's better to check the underlying implementation and ask Pingdom support as I don't maintain this library actively anymore.

**Comment by captDaylight** [comment]
Ok, good to know. Thanks
