### ISSUE TITLE
0.6.0-beta2 is out

### ISSUE THREAD

**Issue by bebraw** [bebraw/pingdom-api#6]
@lwille I pushed a beta with PUT API. Can you check it out and make sure it works for you?

**Comment by bebraw** [comment]
@lwille Forgot to mention, you can get the beta version easily with `npm i pingdom-api@beta`.

**Comment by bebraw** [comment]
@lwille Updated the PUT section a bit (typo there) + added support for DELETE (not tested) at beta2.

It would be awesome to write a little test suite for this...

**Comment by lwille** [comment]
Just updated to beta2. `updateChecks` is working like a charm. Personally I don't need `DELETE` for now.

Would you create a separate issue for testing?

**Comment by bebraw** [comment]
> Would you mind creating a separate issue for the test suite?

We have a rough, mock based suite implemented. I added issues for the missing bits (#8, #9).
